In [4]:
import numpy as np 
print(np.__version__)

2.4.1


whenever we ant to use numpy , you have to import numpy 

In [ ]:
import numpy as np 

a = np.array([34,96,73,69])
print(a)

[34 96 73 69]


array() : it is used to convert tuple, list into numpy array 

In [5]:
import numpy as np 

x = np.array([78.90,80.34,67.1,44])
print(x)
print(type(x))

[78.9  80.34 67.1  44.  ]
<class 'numpy.ndarray'>


type(): it is used to return data type .
numpy array element's type is numpy.ndarray

In [ ]:
import numpy as np 

a = np.array([[3,5],[7,9]])
print(a)

[[3 5]
 [7 9]]


In [11]:
import numpy as np 

a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


zeros():it is used for filling array with 0 

In [ ]:
import numpy as np 

a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np

num = np.ones(8)
n = np.ones((2,4))

print(num)
print(n)

[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
import numpy as np 

num = np.empty(2)
print(num)

[0.00000000e+000 2.12199579e-314]


empty() - it is used to create array without assigning values but contains garbage values 

In [24]:
import numpy as np

a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


arange() - it is similar to range() in python 

In [25]:
import numpy as np 

a = np.linspace(1,10,11)
print(a)

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [26]:
import numpy as np 

a = np.linspace(1,3,1)
print(a)

[1.]


In [27]:
import numpy as np 

a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [29]:
import numpy as np

a = np.array([[42,67,21],
              [89,65,90],
              [56,39,67]])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(3, 3)
9
int64


ndim - number od dimensions 
shape - number of (rows,columns)
size - number of total elements 
dtype - data type of element 

In [30]:
import numpy as np 

a = np.array([5,2,7,0,9,1])

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)


1
(6,)
6
int64


In [33]:
import numpy as np 

a = np.array([34,28,49,51])
print(a)
print(a.dtype)

b = a.astype(float)
print(b)
print(b.dtype)

[34 28 49 51]
int64
[34. 28. 49. 51.]
float64


In [34]:
import numpy as np 

a = np.array([59,52,60,93])

print(a[0])
print(a[2])
print(a[-1])

59
60
93


In [ ]:
import numpy as np 

n = np.array([
    [29,81],
    [73,70]
])

print(n[0 , 0])
print(n[0 , 1])
print(n[1 , 1])

print(n[0]) # printing complete rows
print(n[:,1]) # printing complete columns


29
81
70
[29 81]
[81 70]


In [ ]:
import numpy as np 

x = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(x[0, 0, 0])   # Block 0, Row 0, Col 0
print(x[0, 1, 1])   # Block 0, Row 1, Col 1
print(x[1, 0, 1])   # Block 1, Row 0, Col 1

print(x[0]) # printing whole block 

1
4
6
[[1 2]
 [3 4]]


In [46]:
import numpy as np 

a = np.array([10,20,30,40,50,60,70,80,90])

print(a[1:4])
print(a[:3])
print(a[:-1])
print(a[4:])
print(a[::-1])

[20 30 40]
[10 20 30]
[10 20 30 40 50 60 70 80]
[50 60 70 80 90]
[90 80 70 60 50 40 30 20 10]


In [47]:
import numpy as np 

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0:2 , :])
print(a[ : , 1:3])
print(a[1:2 , 1:2])
print(a[0:2 , 0:2])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[[5]]
[[1 2]
 [4 5]]


In [48]:
import numpy as np 

a = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(a[0,:,:])
print(a[1,0,:])
print(a[1,1,1])

[[1 2 3]
 [4 5 6]]
[7 8 9]
11


In [9]:
import numpy as np 

arr = np.array([12,84,30,58,21,42,10])

print(arr > 10)
print(arr[arr < 50])
print(arr[(arr > 20) & (arr > 80)])
print(arr[(arr > 10) | (arr < 80)])

m = arr < 20
print(arr[m])

arr[arr > 20] = 0
print(arr)


[ True  True  True  True  True  True False]
[12 30 21 42 10]
[84]
[12 84 30 58 21 42 10]
[12 10]
[12  0  0  0  0  0 10]


In [11]:
import numpy as np 

arr = np.array([10,20,30,40,50,60,70,80,90])

b = np.where(arr > 50)
print(b)

c = np.where(arr > 50 , 1 , 0)
print(c)

(array([5, 6, 7, 8]),)
[0 0 0 0 0 1 1 1 1]


In [22]:
#fancy indexing 
import numpy as np 

# 1D array
arr = np.array([7,30,10,52,78])

print(arr[[1,3,2]]) # mention specific indexing 
print(arr[[4,4,1]]) # repeating and changing order 

# 2D array 
a2 = np.array([
    [1,2,3],
    [75,92,37],
    [12,95,46]
])

print(a2[[0,2]]) # accessing only rows 
print(a2[:,[0,2]]) # accessing only columns
print(a2[[1,2],[0,1]]) # row-column pair selection (1,0) , (2,1)

# 3D array 
a3 = np.array([
    [
        [2,89,10],
        [87,84,46]
    ],
    [
        [12,38,52],
        [39,52,65]
    ]
])

print(a3[[0]]) # accessing specific block 
print(a3[[1,0]]) # accessing specific block
print(a3[[1,0],[0,1],[2,2]]) # accessing specific element 


[30 52 10]
[78 78 30]
[[ 1  2  3]
 [12 95 46]]
[[ 1  3]
 [75 37]
 [12 46]]
[75 95]
[[[ 2 89 10]
  [87 84 46]]]
[[[12 38 52]
  [39 52 65]]

 [[ 2 89 10]
  [87 84 46]]]
[52 46]


In [ ]:
# Arithematic operation on 1D array

import numpy as np

a = np.array([10,20,30,40,50,60])
b = np.array([1,2,3,4,5,6])

print(a + b)
print(a + 10)
print(a - 5)
print(a * b)
print(a / b)


[11 22 33 44 55 66]
[20 30 40 50 60 70]
[ 5 15 25 35 45 55]
[ 10  40  90 160 250 360]
[10. 10. 10. 10. 10. 10.]


In [ ]:
#arithmatic operation on 2D array 

import numpy as np 

a1 = np.array([
    [35,74,29],
    [54,79,26]
])

a2 = np.array([
    [1,4,7],
    [3,9,2]
])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


[11 22 33 44 55 66]
[ 9 18 27 36 45 54]
[ 10  40  90 160 250 360]
[10. 10. 10. 10. 10. 10.]


In [31]:
# Arithmetic opration on 1D and 2D array 

a1 = np.array([
        [12,72,90],
        [39,67,47]
])
a2 = np.array([89,36,84])

print(a1 + a2)


[[101 108 174]
 [128 103 131]]


In [39]:
# Universal functions 

a1 = np.array([12,63,70])

a2 = np.array([
    [48,39,72],
    [87,54,53]
])

print(np.add(a1 , a2))
print(np.subtract(a2 , a1))
print(np.multiply(a2 , a1))
print(np.divide(a2 , a1))
print(np.multiply(np.add(a1 , 6) , 7))

[[ 60 102 142]
 [ 99 117 123]]
[[ 36 -24   2]
 [ 75  -9 -17]]
[[ 576 2457 5040]
 [1044 3402 3710]]
[[4.         0.61904762 1.02857143]
 [7.25       0.85714286 0.75714286]]
[126 483 532]


In [41]:
# Aggregate function 

import numpy as np 

a1 = np.array([10,20,30,40,50])

print(np.sum(a1))
print(np.mean(a1))
print(np.min(a1))
print(np.max(a1))
print(np.median(a1))
print(np.std(a1))

150
30.0
10
50
30.0
14.142135623730951


In [ ]:
# Axis concept 

a1 = np.array([
    [56,39,76],
    [36,67,37]
])

print(np.sum(a1 , axis=0)) # remove row - work on column
print(np.min(a1 , axis=1)) # remove column - work on row 
print(np.max(a1 , axis=0))

[ 92 106 113]
[39 36]
[56 67 76]
